# Krótkie wprowadzenie do `numpy`

`Numpy` to najpopularniejsza bibiloteka Pythona do obliczeń numerycznych. Opracowana przez Travisa Oliphanta w 2005 r. jako następca bibliotek `numarray` oraz `numeric`.
Oferuje wygodny interfejs programistyczny oraz bardzo dobrą wydajność w porównaniu do "czytego" Pythona.

`Numpy` leży u podstaw popularności j. Python w dziedzinie uczenia maszynowego, w tym bibliotek `SciPy`, `Pandas`, `TensorFlow` oraz `PyTorch`

In [9]:
import numpy as np

## Tablice `ndarray` -- tworzenie

Podstawowym obiektem `numpy` jest ndarray (n-dimensional array), czyli uogólnienie wektorów i macierzy na dowolną liczbę wymiarów. Elementy ndarray są tego samego **typu** i przechowywane w **ciągłym** obszarze pamięci.

In [10]:
# Tworzenie tablic wielowymiarowych 1D, 2D, 3D
arr1d = np.array([1, 2, 3])

arr2d = np.array([[1, 2],
                  [3, 4]])

arr3d = np.array([[[1], [2]],
                  [[3], [4]]])

arr1d.shape, arr2d.shape, arr3d.shape


((3,), (2, 2), (2, 2, 1))

In [11]:
# Różne sposoby tworzenia tablic
empty = np.empty((3, 4))
zeros = np.zeros((3, 4), dtype=np.int32)
zeros_b = np.zeros_like(empty)
ones = np.ones((3, 4))
rand = np.random.rand(3, 4)

empty, zeros, ones, rand

(array([[0.22535644, 0.47365253, 0.18766358, 0.31772811],
        [0.76457806, 0.37998092, 0.80479619, 0.67631959],
        [0.97654192, 0.68067153, 0.44742156, 0.86560895]]),
 array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=int32),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0.54634524, 0.49224556, 0.1610869 , 0.18530644],
        [0.30133198, 0.73455476, 0.0681147 , 0.1783022 ],
        [0.7619796 , 0.48716216, 0.01729874, 0.86929567]]))

In [12]:
empty.dtype, zeros.dtype


(dtype('float64'), dtype('int32'))

In [13]:
np.arange(-5, 5, 2)

array([-5, -3, -1,  1,  3])

In [14]:
np.linspace(-5, 5, 21)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [15]:
np.linspace(-5, 5, 21).astype(np.int32)

array([-5, -4, -4, -3, -3, -2, -2, -1, -1,  0,  0,  0,  1,  1,  2,  2,  3,
        3,  4,  4,  5], dtype=int32)

## Widok

Numpy używa koncepcji _widoków_ (ang. view) do optymalizacji zużycia pamięci, ale również szybkości działania. Tam gdzie to możliwe, zamiast nowej instancji tablicy tworzony jest *widok*.

In [16]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = a[0, :]  # Pierwszy wiersz macierzy a
b[0] = 99  # Uwaga!
a, b

(array([[99,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([99,  2,  3,  4]))

In [17]:
f'{b.base is a =}\
  {b.flags.owndata = }'

'b.base is a =True  b.flags.owndata = False'

In [18]:
b = a.copy()
f'{b.base is a =}\
  {b.flags.owndata = }'

'b.base is a =False  b.flags.owndata = True'

In [19]:
a[:,:].flags.owndata

False

## Transpozycja, zmiana rozmiaru oraz liczby wymiarów

In [20]:
# Symulacja tworzenia obrazu w skali szarości 28x28 (np. ze zbioru MNIST)
image = np.random.rand(28, 28)
print("\nWymiary oryginalne:", image.shape)

# Jeżeli sieć potrzebuje wektora to możemy zmienić wymiary (1 sample, 784 features)
input_vector = image.reshape((1, -1))   # lub image.reshape((1, 784))
print("Nowe wymiary:", input_vector.shape)



Wymiary oryginalne: (28, 28)
Nowe wymiary: (1, 784)


In [21]:
matrix = np.array([[1, 2], [3, 4], [5, 6]])
print("Oryginalna:\n", matrix)

transposed_matrix = matrix.T
print("\nTransponowana:\n", transposed_matrix)


Oryginalna:
 [[1 2]
 [3 4]
 [5 6]]

Transponowana:
 [[1 3 5]
 [2 4 6]]


In [22]:
# Wstrzykiwanie dodatkowego wymiaru
# Załóżmy, że mamy ciąg, ale potrzebujemy macierzy (lub listy ciągów)
wektor = np.array([1,2,3])
print(f'{wektor = }\n{wektor.shape = }')

macierz = wektor[np.newaxis, :]
print(f'{macierz = }\n{macierz.shape = }')

wektor = array([1, 2, 3])
wektor.shape = (3,)
macierz = array([[1, 2, 3]])
macierz.shape = (1, 3)


In [23]:
# Usuń pierwszy wymiar (o rozmiarze 1) z macierzy:
macierz.squeeze()

array([1, 2, 3])

## Składanie

Składanie (ang. stacking) pozwala nam na wygodne łączenie tablic, np. przykładów z danych wejściowych.

In [24]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

# Połącz wektory pionowo
v_stack = np.vstack((a1, a2))
print("Poskładane:\n", v_stack)

Poskładane:
 [[1 2 3]
 [4 5 6]]


In [25]:
# Składanie wektorów kolumnowych
print(a1.reshape(-1, 1))
# Stack arrays horizontally
h_stack = np.hstack((a1.reshape(-1, 1), a2.reshape(-1, 1)))
print("\nHorizontal stack:\n", h_stack)


[[1]
 [2]
 [3]]

Horizontal stack:
 [[1 4]
 [2 5]
 [3 6]]


## Podział


In [26]:
# Zbiór danych z 10 przykładami:
data = np.random.rand(10, 5)

# Podział na część treningową (80%) i testową (20%)
train_data, test_data = np.split(data, [ 80*len(data) // 100 ])
print("Training data shape:", train_data.shape)
print("Testing data shape:", test_data.shape)


Training data shape: (8, 5)
Testing data shape: (2, 5)



Podział dużych tablic może się przydać, np. gdy chcemy uzyskać porcje (ang. batches) do treningu.

In [27]:
# Symulacja danych wejściowych (100 próbek, 784 cechy)
data = np.random.rand(100, 784)

# Wymieszaj dane (ważne przed podziałem na partie)
np.random.shuffle(data)

# Zdefiniuj rozmiar partii
batch_size = 20

# Oblicz liczbę partii
num_batches = data.shape[0] // batch_size

# Podziel dane na partie
batches = np.array_split(data, num_batches)
print(f"Całkowita liczba partii: {len(batches)}")

# Wyświetl kształt każdej partii
for i, batch in enumerate(batches):
    print(f"Partia {i+1} kształt: {batch.shape}")


Całkowita liczba partii: 5
Partia 1 kształt: (20, 784)
Partia 2 kształt: (20, 784)
Partia 3 kształt: (20, 784)
Partia 4 kształt: (20, 784)
Partia 5 kształt: (20, 784)


## Indeksowanie, maskowanie

In [28]:
a = np.arange(1,7).reshape((2,3))
print(f'{a = }\n{a[1,2] = }\n{a[1] = }\n{a[:,1] = }')

a = array([[1, 2, 3],
       [4, 5, 6]])
a[1,2] = np.int64(6)
a[1] = array([4, 5, 6])
a[:,1] = array([2, 5])


In [29]:
mask = a > 3
mask, a[mask]

(array([[False, False, False],
        [ True,  True,  True]]),
 array([4, 5, 6]))

In [30]:
np.where(a > 3, a, -1)

array([[-1, -1, -1],
       [ 4,  5,  6]])

## Rozgłaszanie

Rozgłaszanie (ang. broadcasting) w `numpy` ułatwia wykonywanie operacji na danych o różnych wymiarach poprzez automatyczne dopasowanie wymiarów.

In [31]:
a = np.array([1, 2, 3])
b = a + 10
b

array([11, 12, 13])

In [32]:
# Wyjścia neuronów (3 przykłady, 4 neurony)
neuron_outputs = np.array([[1.0, 1.5, 2.0, 2.5],
                           [0.5, 1.0, 1.5, 2.0],
                           [1.5, 2.0, 2.5, 3.0]])

# Obciążenia (bias) dla każdego z 4 neuronów
biases = np.array([0.1, 0.2, 0.3, 0.4])

# Dodaj obciążenia
outputs_with_bias = neuron_outputs + biases
print("Outputs with biases:\n", outputs_with_bias)

Outputs with biases:
 [[1.1 1.7 2.3 2.9]
 [0.6 1.2 1.8 2.4]
 [1.6 2.2 2.8 3.4]]


In [33]:
# Wyjścia sieci klasyfikacyjnej przed normalizacją są często określane
# jako "logits". Wyjście dla batcha z 2 przykładami i 3 klasami:
logits = np.array([[2.0, 1.0, 0.1],
                   [1.0, 3.0, 0.2]])

# Liczymy e^x z logitów:
exp_logits = np.exp(logits)
print("Exponentials of logits:\n", exp_logits)

# Suma po wierszach -- zachowaj wymiary, tj. macierz 2 x 1
sum_exp = np.sum(exp_logits, axis=1, keepdims=True)
print("\nSum of exponentials:\n", sum_exp)

# Oblicz prawdopodobieństwa (softmax) dla każdego przykładu i klasy
softmax_probs = exp_logits / sum_exp
print("\nSoftmax probabilities:\n", softmax_probs)

Exponentials of logits:
 [[ 7.3890561   2.71828183  1.10517092]
 [ 2.71828183 20.08553692  1.22140276]]

Sum of exponentials:
 [[11.21250885]
 [24.02522151]]

Softmax probabilities:
 [[0.65900114 0.24243297 0.09856589]
 [0.11314284 0.8360188  0.05083836]]


### Podsumowanie zasad rozgłaszania

* Zaczynij od najbardziej zewnętrznych (prawych) wymiarów.
* Jeśli tablice mają różną liczbę wymiarów, _dodaj jedynki_ na początku kształtu mniejszej tablicy.
* Dla każdego wymiaru rozmiary muszą być _równe lub wynosić jeden._
* Kształt wynikowej tablicy to maksymalny rozmiar wzdłuż każdego wymiaru.
* Tablice są zgodne do broadcastingu, jeśli spełniają wszystkie powyższe zasady.

In [34]:
# A ma wymiary (4, 3, 2)
A = np.ones((4, 3, 2))

# B ma wymiary (   3, 1)
B = np.array([
    [1],
    [2],
    [3],
])

# Dodaj wymiar (od lewej) do B: (1, 3, 1)
# Porównaj poszczególne wymiary:
# 4 vs 1 → 4 (rozgłaszanie wart. z B)
# 3 vs 3 → 3
# 2 vs 1 → 2 (rozgłaszanie wart. z B)
# Wynikowe wymiary: (4, 3, 2)
C = A + B
C

array([[[2., 2.],
        [3., 3.],
        [4., 4.]],

       [[2., 2.],
        [3., 3.],
        [4., 4.]],

       [[2., 2.],
        [3., 3.],
        [4., 4.]],

       [[2., 2.],
        [3., 3.],
        [4., 4.]]])

## Indeksowanie operacji

Parametr `axis` wielu operacji `numpy` odnosi się do wymiaru **wdłuż** którego wykonywana jest operacja.
Jest to kierunek w którym rosną indeksy tablicy dla wymiaru związanego z osią.

Tablica wielowymiarowa ma tyle "osi" ile wymiarów.

* `axis=0` odnosi się do pierwszego wymiaru; w macierzy (2D) to _wiersze_
* `axis=1` odnosi się do drugiego wymiaru; w macierzy (2D) to _kolumny_

Podsumowanie:
* `axis=None` - wykonaj operacje na całej tablicy (spłaszczonej).
* `axis=0`: wzdłuż wierszy (dla 2D), czyli dane do operacji pochodzą z kolejnych wierszy.
* `axis=1`: wzdłuż kolumn (dla 2D), czyli kolejne elementy pochodzą z kolejnych kolumn.

Oś wg której wykonywana jest operacja ulega "spłaszczeniu", czyli jeśli wykonujemy sumowanie z param. `axis=0`, wszystkie wiersze zostaną połączone w jeden poprzez dodanie elementów na odpowiednich pozycjach (kolumny).


In [35]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

total_sum = np.sum(a, axis=None)

col_sums = np.sum(a, axis=0)  # dane pochodzą z kolejnych wierszy

row_sums = np.sum(a, axis=1)  # dane pochodzą z kolejnych kolumn

total_sum, col_sums, row_sums

(np.int64(21), array([5, 7, 9]), array([ 6, 15]))

In [36]:
# Wyjścia sieci (batch size of 4)
layer_outputs = np.array([[0.1, 0.2, 0.3],
                          [0.1, 0.3, 0.5],
                          [0.2, 0.2, 0.2],
                          [0.3, 0.4, 0.5]])

# Średnia ze wszystkich batchy
mean_output = np.mean(layer_outputs, axis=0)
print("Mean output:", mean_output)

# Odch. standardowe
std_output = np.std(layer_outputs, axis=0)
print("Standard deviation:", std_output)


Mean output: [0.175 0.275 0.375]
Standard deviation: [0.08291562 0.08291562 0.12990381]


## Mnożenie macierzy

In [37]:
# Wejścia sieci (batch dla 2 przykładów z 3 cechami)
inputs = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Macierz wag (3 wejścia, 2 neurony)
weights = np.array([[0.1, 0.2],
                    [0.3, 0.4],
                    [0.5, 0.6]])

output = np.dot(inputs, weights)
print("Output:\n", output)

Output:
 [[2.2 2.8]
 [4.9 6.4]]
